### ISSUE TITLE
Krit Practice Result

### ISSUE THREAD

**Issue by KritGG** [hell-s-code/linq-practice#1]
using linq_practice.Utils;
using linqpractice.DataSource;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
/////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Practice LINQ C#
/// ฝึกใช้คำสั่งต่างๆ 
/// DataSource คือ Employees (ข้อมูลพนักงาน)
/// เมื่อ Run Code ห้ามมี Error หรือ Exception ใดๆ
/// โจทย์ที่ให้ทำเป็น Method ส่วนใหญ่ที่ใช้ แต่ไม่ใช่ทั้งหมดที่มีใน Linq ในบางสถานะการณ์อาจจะต้องใช้ Method ที่ไม่มีใน Practice นี้
///
/////////////////////////////////////////////////////////////////////////////////////////////////
List<Employee> Employees = new DataSources().Employees; // DataSource
Utils utils = new Utils();

#region Filter Data

#region No.1 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีชื่อขึ้นต้นด้วยตัวอักษร h
Employees.Where(e => e.FirstName.StartsWith("h", StringComparison.OrdinalIgnoreCase));
#endregion

#region No.2 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีเงินเดือนมากกว่า 30,000 และมีชื่อขึ้นต้นด้วยตัวอักษร k
Employees.Where(e => e.FirstName.StartsWith("k", StringComparison.OrdinalIgnoreCase) && e.Salary > 30000);
#endregion

#region No.3 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีอายุน้อยกว่า 25 ปี และมีเงินเดือนมากกว่า 15,000
List<Employee> test = Employees.Where(e => utils.CalculateAge(e.Birthday) < 25).ToList();
Console.WriteLine(test);
#endregion

#region No.4 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีอายุมากกว่า 50 ปี และมีชื่อลงท้ายด้วยตัวอักษร n
List<Employee> No4 = Employees.Where(e => utils.CalculateAge(e.Birthday) > 50 && e.FirstName.EndsWith("n", StringComparison.OrdinalIgnoreCase)).ToList();;
Console.WriteLine(No4);
#endregion

#region No.5 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีอายุระหว่าง 20 - 40 ปี และมีเงินเดือนน้อยกว่าหรือเท่ากับ 25,000 และชื่อขึ้นต้นด้วยตัวอักษร j หรือมีตัวอักษร o อยู่ทีนามสกุล
List<Employee> No5 = Employees.Where(e => utils.CalculateAge(e.Birthday) >= 20 && utils.CalculateAge(e.Birthday) <= 40 && e.Salary <= 25000 &
(e.FirstName.StartsWith("j", StringComparison.OrdinalIgnoreCase) || e.LastName.Contains("o"))).ToList(); ;
Console.WriteLine(No5);
#endregion

#endregion

#region Projection Operations

#region No.1 จงแสดงข้อมูลของพนักงานทั้งหมด โดยจะแสดง Firstname, Lastname
Employees.Select(e => new { e.FirstName , e.LastName});
#endregion

#region No.2 จงแสดงข้อมูลพนักงานที่มีอายุมากกว่า 30 ปี โดยจะแสดง FullName(ชื่อ + นามสกุล) และ Age(อายุ xx ปี) และ Salary

Employees.Where(e => utils.CalculateAge(e.Birthday) > 30)
    .Select(s => new
{
    FullName = s.FirstName + ' ' + s.LastName,
    Age = "อายุ " + utils.CalculateAge(s.Birthday) + " ปี",
    s.Salary
}).ToList();

#endregion

#region No.3 จงแสดงข้อมูลพนักงานที่มีชื่อลงท้ายด้วยตัว m โดยจะแสดง FirstName(แสดงเพียง 3 ตัวอักษรจากด้านหน้า), LastName(แสดงเพียง 2 ตัวอักษรจากด้านหลัง)
Employees.Where(e => e.FirstName.EndsWith("m", StringComparison.OrdinalIgnoreCase)).Select(s => new 
{
    FirstName = s.FirstName.Substring(0, 3) ,
    LastName = s.LastName.Substring(s.LastName.Length - 2) 
}).ToList();

#endregion

#region No.4 จงแสดงข้อมูลพนักงานที่มีเงินเดินมากกว่า 15,000 บาท โดยจะแสดง ShotName(ชื่อจริง+_+นามสกุลตัวอักษรแรก 1 ตัวอักษร), Gender, Salary(xxxx บาท)

Employees.Where(e => e.Salary > 15000).Select(s => new
{
    ShotName = s.FirstName + " " + s.LastName.Substring(0, 1),
    s.Gender,
    Salary = s.Salary + " บาท"
});

#endregion

#region No.5 จงแสดงข้อมูลพนักงานที่มี Id มากกว่าหรือเท่ากับ 70 โดยจะแสดง FistName(ตัวพิมพ์ใหญ่), LastName(ตัวพิมพ์ใหญ่), age(อายุ xx ปี), Salary(มีเงิน xx บาท)
Employees.Where(e => e.Id >= 70).Select(s => new
{
    FirstName = s.FirstName.ToUpper(),
    LastName = s.LastName.ToUpper(),
    Age = "อายุ " + utils.CalculateAge(s.Birthday) + "ปี",
    Salary = "มีเงิน " + s.Salary +  " บาท"
});
#endregion

#endregion

#region Aggregation Operations

#region No.1 จงแสดงผลรวมของจำนวนเงินทั้งของพนักงาน

Employees.Sum(s => s.Salary);

#endregion

#region No.2 จงแสดงอายุเฉลี่ยของพนักงานทั้งหมด
Employees.Average(s => utils.CalculateAge(s.Birthday));
#endregion

#region No.3 จงแสดงเงินเดือนสูงสุดของพนักงานทั้งหมด

Employees.Max(m => m.Salary);

#endregion

#region No.4 จงแสดงจำนวนน้อยที่สุดของพนักงานทั้งหมด

Employees.Min(m => m.Salary);

#endregion

#region No.5 จงแสดงจำนวนพนักงานทั้งหมด

Employees.Count();

#endregion

#region No.6 จงแสดงผลรวมของจำนวนเงินทั้งหมดของพนักงานโดยไม่ใช้ Sum

int count = Employees.Count();
decimal avg = Employees.Average(m => m.Salary);
decimal result = avg * count;
Console.WriteLine(result);

#endregion

#endregion

#region Element Operations

#region No.1 จงแสดงข้อมูลพนักงานที่มีอายุมากกว่า 30 ปี ให้แสดงข้อมูลแรกที่เจอ

Employees.First(e => utils.CalculateAge(e.Birthday) > 30);

#endregion

#region No.2 จงแสดงข้อมูลพนักงานที่มีอายุมากกว่า 30 ปี ให้แสดงข้อมูลสุดท้ายที่เจอ

Employees.Last(e => utils.CalculateAge(e.Birthday) > 30);

#endregion

#region No.3 จงแสดงข้อมูลพนักงานที่มีเงินเดือนมากกว่า 20,000 ให้แสดงข้อมูลแรกที่เจอ โดยจะแสดง FullName(ชื่อ+นามสกุล), JobTitle, Salary(xx บาท)

Employees.Where(e => e.Salary > 20000).Select(e => new {
    FullName = e.FirstName + " " + e.LastName,
    e.JobTitle,
    Salary = e.Salary + " บาท" 
}).FirstOrDefault();

#endregion

#region No.4 จงแสดงข้อมูลพนักงานที่มีเงินเดือนมากกว่า 20,000 ให้แสดงข้อมูลสุดท้ายที่เจอ โดยจะแสดง FullName(ชื่อ+นามสกุล), JobTitle, Salary(xx บาท)

Employees.Where(e => e.Salary > 20000).Select(s => new
{
    FullName = s.FirstName + " " + s.LastName,
    s.JobTitle,
    Salary = s.Salary + " บาท"
}).LastOrDefault();

#endregion

#endregion

#region Partitioning Data

#region No.1 จงแสดงข้อมูลพนักงานที่มีตัวอักษร m อยู่ในชื่อ เอาแค่ 10 ตัวแรกของข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)

Employees.Where(e => e.FirstName.Contains("m"))
    .Select(s => new
    {
    ShortName = s.FirstName + " " + s.LastName.Substring(0, 1),
    Salary = s.Salary + " บาท"
    })
    .Take(10);

#endregion

#region No.2 จงแสดงข้อมูลพนักงานที่มีตัวอักษร a อยู่ในชื่อ เอาแค่ 10 ตัวสุดท้ายของข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)

Employees.Where(e => e.FirstName.Contains("a"))
        .Select(s => new
        {
            ShortName = s.FirstName + " " + s.LastName.Substring(0, 1),
            Salary = s.Salary + " บาท"
        })
        .Reverse().Take(10);

#endregion

#region No.3 จงแสดงข้อมูลพนักงานที่มีตัวอักษร b อยู่ในชื่อ ไม่เอา 10 ตัวแรกของข้อมูลและเอาข้อมูลเพียง 5 ข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)

Employees.Where(e => e.FirstName.Contains("b"))
    .Select(s => new
    {
        ShortName = s.FirstName + " " + s.LastName.Substring (0, 1),
        Salary = s.Salary + " บาท"
    })
    .Skip(10).Take(5);

#endregion

#region No.4 จงแสดงข้อมูลพนักงานที่มีตัวอักษร c อยู่ในชื่อ ไม่เอา 10 ตัวสุดท้ายของข้อมูลและเอาข้อมูลเพียง 5 ข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)

Employees.Where(e => e.FirstName.Contains("c"))
    .Select(s => new
    {
        ShortName = s.FirstName + " " + s.LastName.Substring(0, 1),
        Salary = s.Salary + " บาท"
    })
    .Reverse().Skip(10).Take(5);

#endregion

#endregion

#region Sorting Data

#region No.1 จงเรียงลำดับข้อมูลพนักงานเงินเดือนจากมากไปน้อย

Employees.OrderByDescending(e => e.Salary);

#endregion

#region No.2 จงเรียงลำดับตามตัวอักษร JonTitle ของพนักงานจากน้อยไปมาก

Employees.OrderBy(e => e.JobTitle);

#endregion

#region No.3 จงเรียงลำดับชื่อพนักงานจากมากไปน้อยและนามสกุลพนักงานจากน้อยไปมาก

Employees.OrderByDescending(obd => obd.FirstName).ThenBy(tb => tb.LastName);

#endregion

#region No.4 จงเรียงลำดับข้อมูลพนักงานแบบย้อนกลับ เช่น นำข้อมูลสุดท้ายมาแทนตัวแรกตามลำดับ

Employees.Reverse();

//debugไม่ได้ รอถามพี่เอิธ

#endregion

#endregion

#region Quantifier Operations

#region No.1 จงเขียนคำสั่ง Linq เพื่อตรวจสอบว่า จากข้อมูลพนักงานทั้งหมดมีคนที่มีอายุเท่ากับ 30 ปีไหม
Employees.Any(e => utils.CalculateAge(e.Birthday) == 30);
#endregion

#region No.2 จงเขียนคำสั่ง Linq เพื่อตรวจสอบว่า จากข้อมูลพนักงานทั้งหมดทุกคนมีเงินเดือนใช่หรือไม่

Employees.All(e => e.Salary > 0 && e.Salary != null);

#endregion

#region No.3 จงเขียนคำสั่งเพื่อตรวจสอบว่าพนักงานที่มี Id = 69 มีอยู่ในข้อมูลพนักงานทั้งหมดจาก DataSource หรือไม่ โดยไม่ใช้ Where

Employees.Any(e => e.Id == 69);

#endregion

#endregion

#region Grouping Data

#region No.1 จงแสดงข้อมูลเพศทั้งหมดของพนักงาน(ห้ามซ้ำ) โดยแสดง Gender

Employees.Select(s => s.Gender).Distinct();

#endregion

#region No.2 จงแสดงข้อมูลแต่ละเพศมีเงินเดือนมากสุดเท่าใด โดยแสดง Gender, Salary(xx บาท)

Employees.GroupBy(e => e.Gender)
            .Select(s => new
            {
                Gender = s.Key,
                MaxSalary = s.Max(e => e.Salary)
            });

#endregion

#region No.3 จงแสดงข้อมูลแต่ละเพศมีกี่คน โดยแสดง Gender, TotalEmployee(แสดงจำนวนคน)
Employees.GroupBy(e => e.Gender)
            .Select(s => new
            {
                Gender = s.Key,
                TotalEmployee = s.Count()
            });
#endregion

#region No.4 จงแสดงกลุ่มข้อมูลแต่ละเพศมีเงินเดือนเท่าไหร่ โดยแสดง Gender, Salary

Employees.GroupBy(e => e.Gender)
            .Select(s => new
            {
                Gender = s.Key,
                Salary = s.Sum(e => e.Salary)
            });

#endregion

#endregion

**Comment by khaiwhan** [comment]
Incorrect
Filter Data 
 - 3 condition 
 Partitioning Data
  - 2 must use TakeLast 
  - 4 must use SkipLast

**Comment by KritGG** [comment]
Filter Data


#region No.3 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีอายุน้อยกว่า 25 ปี และมีเงินเดือนมากกว่า 15,000
List<Employee> test = Employees.Where(e => utils.CalculateAge(e.Birthday) < 25 && e.Salary > 15000).ToList();
#endregion


Partitioning Data

#region No.2 จงแสดงข้อมูลพนักงานที่มีตัวอักษร a อยู่ในชื่อ เอาแค่ 10 ตัวสุดท้ายของข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)
Employees.Where(e => e.FirstName.Contains("a"))
        .Select(s => new
        {
            ShortName = s.FirstName + " " + s.LastName.Substring(0, 1),
            Salary = s.Salary + " บาท"
        })
        .TakeLast(10);
#endregion

#region No.4 จงแสดงข้อมูลพนักงานที่มีตัวอักษร c อยู่ในชื่อ ไม่เอา 10 ตัวสุดท้ายของข้อมูลและเอาข้อมูลเพียง 5 ข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)
Employees.Where(e => e.FirstName.Contains("c"))
    .Select(s => new
    {
        ShortName = s.FirstName + " " + s.LastName.Substring(0, 1),
        Salary = s.Salary + " บาท"
    })
    .SkipLast(10).Take(5);
#endregion
