### ISSUE TITLE
Atom Practice Result

### ISSUE THREAD

**Issue by phakawatbsoft** [hell-s-code/linq-practice#2]
using linqpractice.Utils;
using linqpractice.DataSource;
/////////////////////////////////////////////////////////////////////////////////////////////////
///
/// Practice LINQ C#
/// ฝึกใช้คำสั่งต่างๆ 
/// DataSource คือ Employees (ข้อมูลพนักงาน)
/// เมื่อ Run Code ห้ามมี Error หรือ Exception ใดๆ
/// โจทย์ที่ให้ทำเป็น Method ส่วนใหญ่ที่ใช้ แต่ไม่ใช่ทั้งหมดที่มีใน Linq ในบางสถานะการณ์อาจจะต้องใช้ Method ที่ไม่มีใน Practice นี้
///
/////////////////////////////////////////////////////////////////////////////////////////////////

//public class Utils // ไฟล์ Class แยก
//public class Utils
//{
//    public int Age(DateTime birthday)
//    {
//        DateTime today = DateTime.Today;
//        return today.Year - birthday.Year;
//    }
//}

Utils utils = new Utils();
List<Employee> Employees = new DataSources().Employees; // DataSource

#region Filter Data

#region No.1 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีชื่อขึ้นต้นด้วยตัวอักษร h
Employees.Where(e => e.FirstName.StartsWith("h" , StringComparison.OrdinalIgnoreCase)).ToList();
#endregion

#region No.2 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีเงินเดือนมากกว่า 30,000 และมีชื่อขึ้นต้นด้วยตัวอักษร k
Employees.Where(e => e.FirstName.StartsWith("k", StringComparison.OrdinalIgnoreCase) && e.Salary > 30000).ToList();
#endregion

#region No.3 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีอายุน้อยกว่า 25 ปี และมีเงินเดือนมากกว่า 15,000
Employees.Where(e => utils.Age(e.Birthday) < 25 && e.Salary > 15000).ToList();
#endregion

#region No.4 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีอายุมากกว่า 50 ปี และมีชื่อลงท้ายด้วยตัวอักษร n
Employees.Where(e => utils.Age(e.Birthday) > 50 && e.FirstName.EndsWith("n", StringComparison.OrdinalIgnoreCase)).ToList();
#endregion

#region No.5 จงแสดงข้อมูลทั้งหมดของพนักงานที่มีอายุระหว่าง 20 - 40 ปี และมีเงินเดือนน้อยกว่าหรือเท่ากับ 25,000 และชื่อขึ้นต้นด้วยตัวอักษร j หรือมีตัวอักษร o อยู่ทีนามสกุล
Employees.Where(e => utils.Age(e.Birthday) <= 40 && utils.Age(e.Birthday) >= 20 && e.Salary <= 25000 && (e.FirstName.StartsWith("j", StringComparison.OrdinalIgnoreCase) || e.LastName.Contains("o", StringComparison.OrdinalIgnoreCase))).ToList();
#endregion

#endregion

#region Projection Operations

#region No.1 จงแสดงข้อมูลของพนักงานทั้งหมด โดยจะแสดง Firstname, Lastname
Employees.Select(e=> new {e.FirstName,e.LastName}).ToList();
#endregion

#region No.2 จงแสดงข้อมูลพนักงานที่มีอายุมากกว่า 30 ปี โดยจะแสดง FullName(ชื่อ + นามสกุล) และ Age(อายุ xx ปี) และ Salary
Employees.Where(e => utils.Age(e.Birthday) > 30).Select(x=> new {Fullname = x.FirstName +" "+ x.LastName,Age = utils.Age(x.Birthday), Salary = x.Salary}).ToList();
#endregion

#region No.3 จงแสดงข้อมูลพนักงานที่มีชื่อลงท้ายด้วยตัว m โดยจะแสดง FirstName(แสดงเพียง 3 ตัวอักษรจากด้านหน้า), LastName(แสดงเพียง 2 ตัวอักษรจากด้านหลัง)
Employees.Where(emp => emp.LastName.EndsWith("m")).Select(emp=>new{Firstname = emp.FirstName.Substring(0,3),Lastname = emp.LastName.Substring(emp.LastName.Length-2,2)}).ToList();
#endregion

#region No.4 จงแสดงข้อมูลพนักงานที่มีเงินเดินมากกว่า 15,000 บาท โดยจะแสดง ShotName(ชื่อจริง+_+นามสกุลตัวอักษรแรก 1 ตัวอักษร), Gender, Salary(xxxx บาท)
Employees.Where(emp=> emp.Salary > 15000).Select(emp => new {Shortname = emp.FirstName+" "+emp.LastName.Substring(0,1),Gender = emp.Gender,Salary = emp.Salary}).ToList();
#endregion

#region No.5 จงแสดงข้อมูลพนักงานที่มี Id มากกว่าหรือเท่ากับ 70 โดยจะแสดง FistName(ตัวพิมพ์ใหญ่), LastName(ตัวพิมพ์ใหญ่), age(อายุ xx ปี), Salary(มีเงิน xx บาท)
Employees.Where(emp => emp.Id >= 70).Select(emp => new {firstname = emp.FirstName.ToUpper(),lastname = emp.LastName.ToUpper(), age = utils.Age(emp.Birthday),salary = emp.Salary});
#endregion

#endregion

#region Aggregation Operations

#region No.1 จงแสดงผลรวมของจำนวนเงินทั้งของพนักงาน
Employees.Sum(emp => emp.Salary);
#endregion

#region No.2 จงแสดงอายุเฉลี่ยของพนักงานทั้งหมด
Employees.Average(emp => utils.Age(emp.Birthday));
#endregion

#region No.3 จงแสดงเงินเดือนสูงสุดของพนักงานทั้งหมด
Employees.Max(emp => emp.Salary);
Console.WriteLine();
#endregion

#region No.4 จงแสดงจำนวนน้อยที่สุดของพนักงานทั้งหมด
Employees.Min(emp => emp.Salary);
#endregion

#region No.5 จงแสดงจำนวนพนักงานทั้งหมด
Employees.Select(emp => emp.Id).Count();
#endregion

#region No.6 จงแสดงผลรวมของจำนวนเงินทั้งหมดของพนักงานโดยไม่ใช้ Sum
decimal totalSalary = 0;
Employees.ForEach(emp => totalSalary += emp.Salary);
Console.WriteLine(totalSalary);
#endregion

#endregion

#region Element Operations

#region No.1 จงแสดงข้อมูลพนักงานที่มีอายุมากกว่า 30 ปี ให้แสดงข้อมูลแรกที่เจอ
Employees.Where(emp => utils.Age(emp.Birthday) > 30).FirstOrDefault();
#endregion

#region No.2 จงแสดงข้อมูลพนักงานที่มีอายุมากกว่า 30 ปี ให้แสดงข้อมูลสุดท้ายที่เจอ
Employees.Where(emp => utils.Age(emp.Birthday) > 30).LastOrDefault();
#endregion

#region No.3 จงแสดงข้อมูลพนักงานที่มีเงินเดือนมากกว่า 20,000 ให้แสดงข้อมูลแรกที่เจอ โดยจะแสดง FullName(ชื่อ+นามสกุล), JobTitle, Salary(xx บาท)
Employees.Where(emp=> emp.Salary > 20000).Select(emp => new {Fullname = emp.FirstName+" "+emp.LastName,emp.JobTitle,emp.Salary}).FirstOrDefault();
#endregion

#region No.4 จงแสดงข้อมูลพนักงานที่มีเงินเดือนมากกว่า 20,000 ให้แสดงข้อมูลสุดท้ายที่เจอ โดยจะแสดง FullName(ชื่อ+นามสกุล), JobTitle, Salary(xx บาท)
Employees.Where(emp => emp.Salary > 20000).Select(emp => new { Fullname = emp.FirstName + " " + emp.LastName, emp.JobTitle, emp.Salary }).LastOrDefault();
#endregion

#endregion

#region Partitioning Data

#region No.1 จงแสดงข้อมูลพนักงานที่มีตัวอักษร m อยู่ในชื่อ เอาแค่ 10 ตัวแรกของข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)
Employees.Where(emp => emp.FirstName.Contains("m")).Select(emp => new {ShortName = emp.FirstName+" "+emp.LastName.Substring(0,1),Salary = emp.Salary+" บาท"}).Take(10);
#endregion

#region No.2 จงแสดงข้อมูลพนักงานที่มีตัวอักษร a อยู่ในชื่อ เอาแค่ 10 ตัวสุดท้ายของข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)
Employees.Where(emp=>emp.FirstName.Contains("a")).Select(emp=> new
{
    ShortName = emp.FirstName+" "+emp.LastName.Substring(0,1) ,
    Salary = emp.Salary + " บาท"
}).Reverse().Take(10);
#endregion

#region No.3 จงแสดงข้อมูลพนักงานที่มีตัวอักษร b อยู่ในชื่อ ไม่เอา 10 ตัวแรกของข้อมูลและเอาข้อมูลเพียง 5 ข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)
Employees.Where(emp => emp.FirstName.Contains("b")).Skip(10).Take(5).Select(emp => new
{
    ShortName = emp.FirstName + " " + emp.LastName.Substring(0, 1),
    Salary = emp.Salary + " บาท"
});
#endregion

#region No.4 จงแสดงข้อมูลพนักงานที่มีตัวอักษร c อยู่ในชื่อ ไม่เอา 10 ตัวสุดท้ายของข้อมูลและเอาข้อมูลเพียง 5 ข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)
Employees.Where(emp => emp.FirstName.Contains("c")).Reverse().Skip(10).Reverse().Take(5);
#endregion

#endregion

#region Sorting Data

#region No.1 จงเรียงลำดับข้อมูลพนักงานเงินเดือนจากมากไปน้อย
Employees.OrderByDescending(emp=>emp.Salary);
#endregion

#region No.2 จงเรียงลำดับตามตัวอักษร JonTitle ของพนักงานจากน้อยไปมาก
Employees.OrderBy(emp=>emp.JobTitle);
#endregion

#region No.3 จงเรียงลำดับชื่อพนักงานจากมากไปน้อยและนามสกุลพนักงานจากน้อยไปมาก
Employees.OrderByDescending(emp=>emp.FirstName).OrderBy(emp=>emp.LastName);
#endregion

#region No.4 จงเรียงลำดับข้อมูลพนักงานแบบย้อนกลับ เช่น นำข้อมูลสุดท้ายมาแทนตัวแรกตามลำดับ
Employees.AsEnumerable().Reverse();
#endregion

#endregion

#region Quantifier Operations

#region No.1 จงเขียนคำสั่ง Linq เพื่อตรวจสอบว่า จากข้อมูลพนักงานทั้งหมดมีคนที่มีอายุเท่ากับ 30 ปีไหม
Employees.Any(emp => utils.Age(emp.Birthday) == 30);
#endregion

#region No.2 จงเขียนคำสั่ง Linq เพื่อตรวจสอบว่า จากข้อมูลพนักงานทั้งหมดทุกคนมีเงินเดือนใช่หรือไม่
Employees.All(emp => emp.Salary != null);
#endregion

#region No.3 จงเขียนคำสั่งเพื่อตรวจสอบว่าพนักงานที่มี Id = 69 มีอยู่ในข้อมูลพนักงานทั้งหมดจาก DataSource หรือไม่ โดยไม่ใช้ Where
Employees.All(emp => emp.Id == 69);
#endregion

#endregion

#region Grouping Data

#region No.1 จงแสดงข้อมูลเพศทั้งหมดของพนักงาน(ห้ามซ้ำ) โดยแสดง Gender
Employees.GroupBy(emp=>emp.Gender);
#endregion

#region No.2 จงแสดงข้อมูลแต่ละเพศมีเงินเดือนมากสุดเท่าใด โดยแสดง Gender, Salary(xx บาท)
Employees.GroupBy(emp => emp.Gender).Select(emp => new {Gender = emp.Key, Salary = emp.Max(emp=>emp.Salary)});
#endregion

#region No.3 จงแสดงข้อมูลแต่ละเพศมีกี่คน โดยแสดง Gender, TotalEmployee(แสดงจำนวนคน)
Employees.GroupBy(emp => emp.Gender).Select(emp => new { Gender = emp.Key, TotalEmp = emp.Count() });
#endregion

#region No.4 จงแสดงกลุ่มข้อมูลแต่ละเพศมีเงินเดือนเท่าไหร่ โดยแสดง Gender, Salary
Employees.GroupBy(emp => emp.Gender).Select(emp => new { Gender = emp.Key, Salary = emp.Sum(emp=>emp.Salary) });
#endregion

#endregion

**Comment by khaiwhan** [comment]
Projection Operations
- 4 Select Incorrect
- 5 Select Incorrect
Element Operations
- 3 Select Incorrect
- 4 Select Incorrect
Partitioning Data
- 2 Inccorect Method
- 4 Inccorect Method
Sorting Data
- 3 Inccorect 
Quantifier Operations
- 3 Inccorect

**Comment by phakawatbsoft** [comment]
Projection Operations

#region No.3 จงแสดงข้อมูลพนักงานที่มีชื่อลงท้ายด้วยตัว m โดยจะแสดง FirstName(แสดงเพียง 3 ตัวอักษรจากด้านหน้า), LastName(แสดงเพียง 2 ตัวอักษรจากด้านหลัง)
Employees.Where(emp => emp.LastName.EndsWith("m")).Select(emp=>new{Firstname = emp.FirstName.Substring(0,3),Lastname = emp.LastName.Substring(emp.LastName.Length-2,2)}).ToList();
#endregion

#region No.4 จงแสดงข้อมูลพนักงานที่มีเงินเดินมากกว่า 15,000 บาท โดยจะแสดง ShotName(ชื่อจริง+_+นามสกุลตัวอักษรแรก 1 ตัวอักษร), Gender, Salary(xxxx บาท)
Employees.Where(emp => emp.Salary > 15000).Select(emp => new { ShortName = emp.FirstName + " " + emp.LastName.Substring(0, 1), Gender = emp.Gender, Salary = emp.Salary + " บาท" });
#endregion

Element Operations

#region No.3 จงแสดงข้อมูลพนักงานที่มีเงินเดือนมากกว่า 20,000 ให้แสดงข้อมูลแรกที่เจอ โดยจะแสดง FullName(ชื่อ+นามสกุล), JobTitle, Salary(xx บาท)
Employees.Where(emp=> emp.Salary > 20000).Select(emp => new {Fullname = emp.FirstName+" "+emp.LastName, JobTitle = emp.JobTitle, Salary = emp.Salary + " บาท" }).FirstOrDefault();
#endregion

#region No.4 จงแสดงข้อมูลพนักงานที่มีเงินเดือนมากกว่า 20,000 ให้แสดงข้อมูลสุดท้ายที่เจอ โดยจะแสดง FullName(ชื่อ+นามสกุล), JobTitle, Salary(xx บาท)
Employees.Where(emp => emp.Salary > 20000).Select(emp => new { Fullname = emp.FirstName + " " + emp.LastName, JobTitle = emp.JobTitle, Salary = emp.Salary + " บาท" }).LastOrDefault();
#endregion

Partitioning Data

#region No.2 จงแสดงข้อมูลพนักงานที่มีตัวอักษร a อยู่ในชื่อ เอาแค่ 10 ตัวสุดท้ายของข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)
Employees.Where(emp=>emp.FirstName.Contains("a")).Select(emp=> new
{
    ShortName = emp.FirstName+" "+emp.LastName.Substring(0,1) ,
    Salary = emp.Salary + " บาท"
}).TakeLast(10);
#endregion

#region No.4 จงแสดงข้อมูลพนักงานที่มีตัวอักษร c อยู่ในชื่อ ไม่เอา 10 ตัวสุดท้ายของข้อมูลและเอาข้อมูลเพียง 5 ข้อมูล โดยจะแสดง ShortName(ชื่อ+.+ตัวแรกของนามสกุล), Salary(xx บาท)
Employees.Where(emp => emp.FirstName.Contains("c")).SkipLast(10).Take(5);
#endregion

Sorting Data

#region No.3 จงเรียงลำดับชื่อพนักงานจากมากไปน้อยและนามสกุลพนักงานจากน้อยไปมาก
Employees.OrderByDescending(emp=>emp.FirstName).ThenBy(emp=>emp.LastName);
#endregion

Quantifier Operations

#region No.3 จงเขียนคำสั่งเพื่อตรวจสอบว่าพนักงานที่มี Id = 69 มีอยู่ในข้อมูลพนักงานทั้งหมดจาก DataSource หรือไม่ โดยไม่ใช้ Where
Employees.Any(emp => emp.Id == 69);
#endregion
